### ISSUE TITLE
cannot post to more then one slack team

### ISSUE THREAD

**Issue by vgrme** [magnetikonline/slack-post#1]
Add more then one webhook url needs to be included in any documentaion like array declaration and looping.

**Comment by magnetikonline** [comment]
Hello @vinaygrajagopal - sorry I missed your message in my email notifications. Can you expand more on what you would like to see?

Thanks

   Peter

**Comment by vgrme** [comment]
Hello @magnetikonline - Thanks for the note. I was looking at an example docs in your current https://github.com/magnetikonline/slackpost#example-usage for adding more then one webhook urls. Something on the lines of declaring an array webhook1:webhook2... and looping the same for payload to be sent.
